# Generated by Django 5.0.6 on 2026-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('termination', 'Termination'), ('confidentiality', 'Confidentiality'), ('renewal', 'Renewal'), ('duration', 'Duration'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
